apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "hello-rails-on-k8s.fullname" . }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          # どのサービスのどのポートに流すか
          serviceName: {{ include "hello-rails-on-k8s.fullname" . }}
          servicePort: 84
