apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-rails-on-k8s.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hello-rails-on-k8s.name" . }}
    helm.sh/chart: {{ include "hello-rails-on-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  # ingress 経由なのでクラスタ内に閉じておく
  type: ClusterIP
  selector:
    # これにマッチした pod に流す
    app.kubernetes.io/name: {{ include "hello-rails-on-k8s.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      # 受信するポート
      port: 84
      # 送信するポート
      # Pod の port 名でも可
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-rails-on-k8s.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hello-rails-on-k8s.name" . }}
    helm.sh/chart: {{ include "hello-rails-on-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: webserver

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-rails-on-k8s.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hello-rails-on-k8s.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: webserver
    spec:
      volumes:
        - name: sockets
          emptyDir: {}
      containers:
        - name: {{ .Values.web.name }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            # service から受けるポート
            - name: http
              containerPort: {{ .Values.web.port.http }}
          volumeMounts:
            - mountPath: /sockets
              name: sockets

        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          # デフォルトで pull しにいってコケるので Never させないようにする
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.app.dbHost }}

          volumeMounts:
            - mountPath: /sockets
              name: sockets
